repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      - id: trailing-whitespace